### ISSUE TITLE
Build fails: missing `suggestion` field in Issue initializers (introduced in 114ac61)

### ISSUE THREAD

**Issue by rexjayx** [guanchuan1314/vow#318]
### Description

The build fails with 40 errors after commit `114ac61` (feat: detect insecure file permissions in Dart/Flutter files) due to missing `suggestion` field in `Issue` struct initializers.

```
error[E0063]: missing field `suggestion` in initializer of `Issue`
```

### Root Cause

Commit `8daa0e2` added `suggestion: Option<String>` to the `Issue` struct in `src/lib.rs`. Commit `114ac61` and related Dart/Flutter analyzer files introduced new `Issue { ... }` constructors without including the `suggestion` field, breaking compilation.

### Affected files

- `src/analyzers/text.rs` (7 locations)
- `src/analyzers/html_analyzer.rs` (9 locations)
- `src/analyzers/css_analyzer.rs` (8 locations)
- `src/analyzers/injection.rs` (5 locations)
- `src/analyzers/type_combinations.rs` (10 locations)

### Fix

Add `suggestion: None,` to all `Issue { ... }` struct initializers missing the field in the above files.
